import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./SessionWrapper"; // Adjust the path based on your file structure

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"></link>

      <body className={inter.className}>
        <SessionWrapper>
          {children}
          
        </SessionWrapper>
        
      </body>
    </html>
  );
}
